changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: "Fixes :bug:"
      labels:
        - bug
    - title: New Features 🎉
      labels:
        - "*"
