changelog:
  exclude:
    labels:
      - ignore-for-release
      - bump
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - "*"
    - title: Fixes :bug:
      labels:
        - fix
